extends "res://tests/IntegrationQA.gd"
## Windowed inspection through real held movement, never teleporting the player.
func run() -> void:
	reparent(get_tree().root)
	render = true
	await frames(10)
	await click_button("准时赴约")
	await click_button("开始赴宴")
	await walk_to(Vector3(0,0,42))
	await walk_to(Vector3(-4.5,0,40))
	await capture("v06-board-start")
	await walk_to(Vector3(0,0,40))
	await walk_to(Vector3(0,0,22))
	await capture("v06-wood-sign")
	await walk_to(Vector3(0,0,-3))
	await walk_to(Vector3(9,0.6,-3))
	check(world.player.position.y > 0.5 and world.player.is_on_floor(), "raised courtyard reached via physical ramp")
	await capture("v06-courtyard-ramp")
	await walk_to(Vector3(0,0,-3))
	check(world.player.position.y < 0.2, "ramp returns to main route")
	await walk_to(Vector3(0,0,-19))
	await walk_to(Vector3(-2.8,0,-17))
	await capture("v06-board-academic")
	await walk_to(Vector3(0,0,-19))
	await walk_to(Vector3(0,0,-27))
	await walk_to(Vector3(15,0,-27))
	await capture("v06-shuttle-reserve")
	await walk_to(Vector3(16.1,0,-32))
	await walk_to(Vector3(16.1,0,-40))
	await capture("v06-road-exit")
	# Return north of the photo backdrop and its collision.
	await walk_to(Vector3(16.1,0,-29))
	await walk_to(Vector3(0,0,-29))
	await walk_to(Vector3(0,0,-48.2))
	await frames(25)
	await capture("v06-foyer")
	await press("interact")
	await click_button("一起进入高桌晚宴")
	check(GameState.get_flag("game_finished"), "world inspection ends through normal friend interaction")
	await capture("v06-tour-ending")
	var file := FileAccess.open("res://tests/artifacts/v06-tour.json", FileAccess.WRITE)
	file.store_string(JSON.stringify({"checks":checks,"failures":failures,"screenshots":screenshot_names,"state":GameState.snapshot()}, "\t"))
	file.close()
	print("IDENTITY TOUR COMPLETE: ",checks," checks, ",failures.size()," failures")
	get_tree().quit(0 if failures.is_empty() else 1)
